// Sanitized QuickDeal feed sample for tests: the real `format=quickDeal` XML
// structure with invented people, phones, emails and coordinates (no real PII
// or feed secret). Three objects exercise the mapping branches:
//   1. RU land (RESALE / LAND, area in sotka, landUse, no title → fallback)
//   2. AE flat (DUBAI / APARTMENT, USD standardized price, installments, complex)
//   3. RU house (RESALE / HOUSE, totalArea in m², rooms, no title → fallback)
export const SAMPLE_FEED_XML = `<?xml version="1.0" encoding="UTF-8"?>
<estate-objects>
  <estate-object>
    <id>1000001</id>
    <feedId>QD_RS_1000001</feedId>
    <dealType>sale</dealType>
    <category>residential</category>
    <realtyType>land</realtyType>
    <address>
      <area>Тестовский</area>
      <areaTypeFull>район</areaTypeFull>
      <country>Россия</country>
      <countryIsoCode>RU</countryIsoCode>
      <region>Тестовская</region>
      <settlement>Тестовка</settlement>
      <settlementTypeFull>село</settlementTypeFull>
      <geoLat>43.100000</geoLat>
      <geoLon>45.700000</geoLon>
    </address>
    <status>active</status>
    <assigned>
      <id>1</id>
      <firstName>Иван</firstName>
      <lastName>Тестов</lastName>
      <email>ivan@example.com</email>
      <mobilePhone>+70000000001</mobilePhone>
    </assigned>
    <images>
      <src><name>https://cdn.example/land/1.jpeg</name><default>true</default></src>
    </images>
    <isHidden>false</isHidden>
    <geoLat>43.135000</geoLat>
    <geoLon>45.730000</geoLon>
    <description>&lt;p&gt;Участок 8 соток. ИЖС.&lt;/p&gt;</description>
    <bargainTerms>
      <price>1500000</price>
      <pricePerSquareMeter>1875</pricePerSquareMeter>
      <currency>rub</currency>
      <standardCurrency>usd</standardCurrency>
      <standardizedPrice>20790</standardizedPrice>
    </bargainTerms>
    <feedSettings>
      <isSendToCompanySite>true</isSendToCompanySite>
    </feedSettings>
    <realty>
      <land>
        <area><value>8</value><unit>sotka</unit></area>
        <permittedLandUseType>individualHousingConstruction</permittedLandUseType>
      </land>
      <waterType>central</waterType>
    </realty>
  </estate-object>
  <estate-object>
    <id>1000002</id>
    <feedId>QD_RS_1000002</feedId>
    <dealType>sale</dealType>
    <category>residential</category>
    <realtyType>flat</realtyType>
    <address>
      <city>Дубай Марина</city>
      <country>ОАЭ</country>
      <countryIsoCode>AE</countryIsoCode>
      <region>Dubai</region>
      <geoLat>25.085251</geoLat>
      <geoLon>55.146461</geoLon>
    </address>
    <status>active</status>
    <assigned>
      <id>2</id>
      <firstName>Админ</firstName>
      <email>admin@example.com</email>
      <mobilePhone>+70000000002</mobilePhone>
    </assigned>
    <images>
      <src><name>https://cdn.example/flat/1.jpeg</name><default>true</default></src>
    </images>
    <isHidden>false</isHidden>
    <isElite>true</isElite>
    <title>Квартира в Дубай Марина 150 кв</title>
    <geoLat>25.089504</geoLat>
    <geoLon>55.145618</geoLon>
    <bargainTerms>
      <price>22000000</price>
      <currency>rub</currency>
      <standardCurrency>usd</standardCurrency>
      <standardizedPrice>304932</standardizedPrice>
      <sale>
        <paymentMethods>cash</paymentMethods>
        <paymentMethods>installments</paymentMethods>
      </sale>
    </bargainTerms>
    <feedSettings>
      <isSendToCompanySite>true</isSendToCompanySite>
    </feedSettings>
    <developmentHouse><id>1</id><name>W Residences Dubai Downtown</name></developmentHouse>
    <realty>
      <roomsCount>2</roomsCount>
      <totalArea><value>155</value><unit>squareMeter</unit></totalArea>
      <floorNumber>3</floorNumber>
    </realty>
    <building>
      <usageStartYear>2025</usageStartYear>
      <floorsCount>30</floorsCount>
      <projectStatus>readySecondary</projectStatus>
    </building>
  </estate-object>
  <estate-object>
    <id>1000003</id>
    <feedId>QD_RS_1000003</feedId>
    <dealType>sale</dealType>
    <category>residential</category>
    <realtyType>house</realtyType>
    <address>
      <area>Гудермесский</area>
      <city>Гудермес</city>
      <country>Россия</country>
      <countryIsoCode>RU</countryIsoCode>
      <region>Чеченская</region>
      <geoLat>43.342854</geoLat>
      <geoLon>46.119144</geoLon>
    </address>
    <status>active</status>
    <assigned>
      <id>3</id>
      <firstName>Пётр</firstName>
      <lastName>Домов</lastName>
      <mobilePhone>+70000000003</mobilePhone>
    </assigned>
    <images>
      <src><name>https://cdn.example/house/1.jpeg</name><default>false</default></src>
      <src><name>https://cdn.example/house/2.jpeg</name><default>true</default></src>
    </images>
    <isHidden>false</isHidden>
    <bargainTerms>
      <price>11500000</price>
      <currency>rub</currency>
      <standardCurrency>usd</standardCurrency>
      <standardizedPrice>159396</standardizedPrice>
    </bargainTerms>
    <feedSettings>
      <isSendToCompanySite>true</isSendToCompanySite>
    </feedSettings>
    <realty>
      <totalArea><value>135</value><unit>squareMeter</unit></totalArea>
      <roomsCount>5</roomsCount>
      <land><area><value>6</value><unit>sotka</unit></area></land>
    </realty>
    <building>
      <floorsCount>1</floorsCount>
      <projectStatus>readySecondary</projectStatus>
    </building>
  </estate-object>
</estate-objects>`
